### ISSUE TITLE
Quick add button?

### ISSUE THREAD

**Issue by DaliMorse** [Stack-in-a-box/chrome-domain-watermarker#6]
Tried this out and it works great! 

Is there a way to add the site you are on to the list without copying and pasting the domain in?
(kind of like adding a favourite?)

**Comment by andidavies92** [comment]
Thanks for the feedback, @DaliMorse! Great suggestion, I'll implement this for the next release 👍

**Comment by andidavies92** [comment]
Thinking about how this might be best from a usability perspective, I could maybe pre-populate the domain field with the current domain when the popup is shown, so that there's only one further click needed to add the current domain while stopping the interface getting too cluttered? Thoughts, @DaliMorse?

**Comment by DaliMorse** [comment]
Yeah, that'd do fine. Just saves having to copy and paste the domain in.

**Comment by andidavies92** [comment]
Nice, I'll do that then 🙂 I'll probably also select all text on field focus so that it's easier to replace it in the use case that you want to enter a different domain, unless you think this might end-up being more of a hindrance than a help (e.g. if you just want to tweak the domain that's in the field)?

**Comment by DaliMorse** [comment]
Yeah, that sounds good to me.

**Comment by andidavies92** [comment]
Depends on #8
